# This is a basic workflow that is manually triggered

name: Main

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "number_provider"
  number_provider:
    # The type of runner that the job will run on
    runs-on: macos-latest

    env:
      RANDOM_NUMBER: -1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # If you are accessing files from the repo, you need to perform a checkout first.
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Randomize number
      run: ./.github/scripts/get_number.sh

  call-print_number_workflow:
    uses: ./.github/workflows/print_number.yaml@print_number
    with:
      number: 99
    secrets: inherit
