# This is a basic workflow that is manually triggered

name: Main

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-print_number_workflow:
    uses: ./.github/workflows/print_number.yaml
    with:
      number: 99
    secrets: inherit
