# This is a basic workflow that is manually triggered

name: Main

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    outputs:
      random-number:
        description: "Random output number"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_number_workflow:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get a random number
      - id: random-number-step
        run: echo "random-number=$(echo ./.github/scripts/get_number.sh)" >> $GITHUB_OUTPUT

  call-print_number_workflow:
    needs: get_number_workflow
    uses: ./.github/workflows/print_number.yaml
    with:
      number: 99
    secrets: inherit
