# This is a basic workflow that is manually triggered

name: Print a number

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
    inputs:
      number:
        description: 'Put a number'
        type: string

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      number:
        # Friendly description to be shown in the UI instead of 'number'
        description: 'Put a number'
        # Default value if no value is explicitly provided
        default: '0'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "print_number"
  print_number:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Print a number step
      run: echo "Hello! You type ${{ inputs.number }} as a number."
